# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: smtc2web.smtc2web.x64
PackageVersion: 0.6.6
PackageLocale: en-US
Publisher: smtc2web
PackageName: smtc2web
License: MIT License
ShortDescription: An software can let OBS show playing media.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
