# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: smtc2web.smtc2web.arm64
PackageVersion: 0.6.6
InstallerType: nullsoft
Installers:
- Architecture: arm64
  InstallerUrl: https://download.smtc2web.org/v0.6.6/smtc2web_0.6.6_arm64-setup.exe
  InstallerSha256: 4162E5EFCE5296F6C2651C73D656FB291B8E2826A2A6A483BA44352F748BB485
ManifestType: installer
ManifestVersion: 1.12.0
